### ISSUE TITLE
Trying to create new user using admin api causes 403

### ISSUE THREAD

**Issue by darthmolen** [skoruba/Duende.IdentityServer.Admin#103]
### Question

When creating a new user via the admin api., I can get a token from the sts, but when I go to use it, it gives me a 403 without any information on what is causing the 403. Is there a way to turn on seeing 403 errors?

```
{
  "alg": "RS256",
  "kid": "0C6B635763B4E5C8CE419C7BB1968AA3",
  "typ": "at+jwt"
}.{
  "iss": "https://sts-dev.mycompany.com",
  "nbf": 1668121628,
  "iat": 1668121628,
  "exp": 1668125228,
  "aud": "mycompany_api",
  "scope": [
    "pakilti_api"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "mycompanyi_api_swaggerui",
  "sub": "60eb4e43-71ba-4350-a75c-999d02fxxxxx",
  "auth_time": 1668103507,
  "idp": "local",
  "name": "xxxxxxx@mycompany.com",
  "sid": "54D3AFCF98B86EA63EFFBBD98E91B873",
  "jti": "415866E246CC4C1D21AB3869F5F9D131"
}.[Signature]
```
![image](https://user-images.githubusercontent.com/533340/201228223-c2ec9be5-a869-4ee6-b529-b9d44333c644.png)

**Comment by skoruba** [comment]
Hi, does your account admin role for getting this information from api?
Thanks

**Comment by skoruba** [comment]
It is fixed. thanks.
