### ISSUE TITLE
ASP.NET Identity table names

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#107]
Hi @skoruba ,

After I installed and used the VS template I noticed that the ASP.NET Identity tables have changed compared to the original ones.

AspNetUsers  -> Users
AspNetRoles -> Roles
...
etc

![image](https://user-images.githubusercontent.com/13006228/208909046-e1df3c2b-a7f0-4134-8778-a35adf0ca515.png)

Our client needs to migrate an existing database where the users are stored in an Identity table with the original table names.
Given that your solution has different names for tables I am trying to estimate the effort I would need to make in order to do the migration correctly.

Can you confirm why was this renaming needed and is there a way I can preserve the tables with original names?

Regards,
Andrei

**Comment by apetrut** [comment]
@eminmesic Thanks, it's really great that the table name are customizable.

**Comment by apetrut** [comment]
@skoruba I have recently taken version 2.3.0 which loads the table names from the configuration file instead of a constants file. I have renamed the fields in configuration to use the AspNet* prefix but the tables were created with the old names.
Can you reproduce that?

**Comment by skoruba** [comment]
Hi @apetrut - yes, you can rename tables, but you need re-generate ef migrations.
