### ISSUE TITLE
License not applied

### ISSUE THREAD

**Issue by egbertn** [skoruba/Duende.IdentityServer.Admin#11]
### Question
It seems that a valid license key is ignored.

    "AdvancedConfiguration": {
        "IssuerUri": "",
        "IdentityServerLicenseKey": "eyJhbG.........................."
    },

(Other options are off)

 "CertificateConfiguration": {

    
        "UseSigningCertificatePfxFile": true,
        "SigningCertificatePfxFilePath": "./mycerttttttttttttttttttt.pfx",
        "SigningCertificatePfxFilePassword": "***********",
### Relevant parts of the log file

*PROBLEM*

**Comment by skoruba** [comment]
I will test it, thanks!

**Comment by egbertn** [comment]
To answer my own question. Sorry to bother with this bogus question. UseSigningCertificatePfxFile is of course, only for signing the jwt. For signing http, (thus ssl) the 'ConfigureKestrel' section can be used.

**Comment by skoruba** [comment]
Thanks, that makes sense.
