### ISSUE TITLE
Access Denied when adding a custom Profile Service 

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#116]
I created a custom ProfileService that adds a list of tenants ids in the JWT token (see below):

![jwt_tenants](https://user-images.githubusercontent.com/13006228/212767515-e6abb2cf-8126-47bf-ad30-238fc3285a5f.png)

When I try to load the IdentityServer Admin page I get this error:

![image](https://user-images.githubusercontent.com/13006228/212767795-8214c70c-9ffc-4a4a-9632-ec6a97847759.png)

@skoruba can you indicate what's causing the issue? If I remove the custom profile service, the Admin page loads fine.

Thanks.

**Comment by skoruba** [comment]
Hi, there is missing claim "role" for administration.

**Comment by apetrut** [comment]
Hi,

I have added the list of roles like this:

```
var roleClaims = context.Subject.FindAll(JwtClaimTypes.Role);
            context.IssuedClaims.AddRange(roleClaims);
```

and it worked.

Thanks a lot.

**Comment by apetrut** [comment]
@skoruba Using v2.3.0 I have added a custom profile service that adds the custom "role" claim to the token. When I test locally and login in the UI I can't see this profile service being called at all and because of that the Admin UI page throws this error:

User.IsInRole must be true for one of the following roles:


I have also added this custom profile service in the StartupHelpers.cs class:

 .AddAspNetIdentity<TUserIdentity>()
 .AddProfileService<TenantProfileService>();

but it doesn't seem to be called.

Only if I use Postman to POST a request to this endpoint: https://sts.skoruba.local/connect/token the custom profile service gets called.

Is there a way to check what claims I have in the token before I load the Admin UI page?

**Comment by apetrut** [comment]
I found the solution eventually in the STS Startup.cs class:

Add this line in the ConfigureServices method: `RegisterForwardedHeaders(services);

and also this method:

public virtual void RegisterForwardedHeaders(IServiceCollection services)
{
    services.Configure<ForwardedHeadersOptions>(options =>
    {
        options.ForwardedHeaders = ForwardedHeaders.All;
        options.KnownNetworks.Clear();
        options.KnownProxies.Clear();
    });
}
and then in the Configure method add this line:

app.UseForwardedHeaders();
