### ISSUE TITLE
Consent screen - can it be skipped?

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#118]
Hi,

I have an Angular app using Duende Admin UI. After the login page the user sees a consent screen like below:

![duende_consent_screen](https://user-images.githubusercontent.com/13006228/213702080-19f649ce-2274-4b81-bd4b-6c6cdbf834f1.png)

Is there a way to skip it?

**Comment by skoruba** [comment]
Hi, sure, you can disable consent screen - there is option in the "Advanced" section - Consent.

**Comment by apetrut** [comment]
Thank you, I found it.
