### ISSUE TITLE
Duende.BFF - can it be integrated?

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#121]
Hi @skoruba,

We want to integrate Duende.BFF with your existing solution. Can you confirm if you tried it and it worked to integrate it?

Does it need integration with our custom back-end APIs that need access tokens or the whole integration is done in the Identity Admin / Admin Api and STS projects?

Thanks.

**Comment by skoruba** [comment]
Hi,
why do you need it for MVC app?

**Comment by apetrut** [comment]
We have an angular application that will redirect the user to the Duende Identity login.
The Duende.BFF contains a front-end host and a back-end host (both in .NET Core).

I wanted to know if we need to integrate the back-end or front-end host with your solution or it is not necessary at all. The documentation on the Duende page is not very precise.

Thanks.

**Comment by skoruba** [comment]
BFF is great for your angular app, you can definitely use it.
