### ISSUE TITLE
Docker-Compose: errors on startup

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#122]
Hi,

I am using the Duende.IdentityServer.Admin Release 1.1.0 and removed PostgreSql and MySql projects from the solution.

Starting the Docker-compose project gives the following errors:
![docker_error_target_process](https://user-images.githubusercontent.com/13006228/214947816-a3826ff7-7e11-46e2-9316-ce9c852f907c.jpg)

and
![docker_error_sa_login](https://user-images.githubusercontent.com/13006228/214947873-be024e92-daf5-48bb-9695-b7e3cdbbddf4.jpg)

Log file:
[log.txt](https://github.com/skoruba/Duende.IdentityServer.Admin/files/10513299/log.txt)

The password Password_123 is the original one as I haven't touched that setting at all.

**Comment by skoruba** [comment]
fixed in 1.2.0
