### ISSUE TITLE
Paging on listing user under some role doen not work properly.

### ISSUE THREAD

**Issue by markogl** [skoruba/Duende.IdentityServer.Admin#133]
When click on pager on RoleUsers page you get error:

![image](https://user-images.githubusercontent.com/22552703/216822994-9c369748-fcee-40e4-a76e-a43b9825f254.png)

Pager does not include role guid into search

**Comment by skoruba** [comment]
You are right, thank you! can you send a PR?

**Comment by skoruba** [comment]
Fixed, thanks!
