### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by apetrut** [skoruba/Duende.IdentityServer.Admin#160]
Hi @skoruba ,

Do you have any plans to upgrade to .NET 7?

**Comment by nandez** [comment]
Hi @apetrut , how are you?
Regarding the upgrade to .NET 7, the issue already exists (#117) as well as an ongoing pull request that addresses the change (#129). We look forward to it being reviewed and merged soon.

**Comment by skoruba** [comment]
Hi guys, thank you for your interest in update to .NET 7, I was busy, I will update it soon. Can you please test mentioned PR?

thanks!

**Comment by mrjamiebowman** [comment]
.NET 8 comes out in November. Are we open to pull requests? I could help.

**Comment by skoruba** [comment]
Hi @mrjamiebowman - sorry for delayed answer. Yes, I will update it. You can also help if you have time. 👍 
Thanks!

**Comment by skoruba** [comment]
Updated to .NET 8 and IdentityServer v7 in version 2.0.0. Thanks! :)
