### ISSUE TITLE
Bug: role users pagination

### ISSUE THREAD

**Issue by daniil-saraev** [skoruba/Duende.IdentityServer.Admin#169]
Hi!
### Describe the bug
There are many users with a certain role. When I go to 'Users' page that displays all the users with that role I can only view the first page, when I try to go to any other page I get an error:
![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/104396056/0c18766d-4f54-4d52-aa97-113a23cc9f64)
And it looks like the problem is somewhere in url generating, because the url looks like this now:
![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/104396056/ba6d8da4-46c9-4541-ad35-825b1f33924b)
while on the first page it's fine:
![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/104396056/faa921fc-f683-47bd-b763-d88ecfd76b84)
The role id parameter disappears for some reason, if I insert it manually - everything works:
![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/104396056/16a13734-d0a9-4e31-878c-2c51700cd1b4)

**Comment by skoruba** [comment]
Hi @daniil-saraev  - thanks!

**Comment by skoruba** [comment]
Fixed
