### ISSUE TITLE
Upgrade to Identity Server 6.3

### ISSUE THREAD

**Issue by colin-freemarketfx** [skoruba/Duende.IdentityServer.Admin#171]
**Is your feature request related to a problem? Please describe.**
In order to ensure compatibility with our copy of identity server, which we would like to upgrade to 6.3, we should have a copy of IdentityServer.Admin that also depends on 6.3.

**Describe the solution you'd like**
Are there any plans in place to produce an upgrade to 6.3, and if so what progress has been made?
At a minimum, an 'early' version that has awareness of the new fields so it doesn't drop any data would be awesome.

**Describe alternatives you've considered**
I've had a bash at this in our [fork ](https://github.com/FreemarketFX/Duende.IdentityServer.Admin), by following the[ instructions provided by Duende](https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.2_to_v6.3/), <strike>but I'm stuck on adding a migration (similar to [this SO issue](https://stackoverflow.com/questions/54799905/your-startup-project-project-doesnt-reference-microsoft-entityframeworkcore-d), I also tried this [solution](https://stackoverflow.com/questions/52536588/your-startup-project-doesnt-reference-microsoft-entityframeworkcore-design)). </strike> I used the add migration script in the build folder as described in the docs, thanks I should have checked there first 😅

**Additional context**
I'm sure I can contribute some time to this effort but would likely need some guidance and have no experience in MySQL or Postgres when it comes to updating those portions.

**Comment by skoruba** [comment]
I updated it to IS version 7.0. on version 2.0.0. Thanks!

**Comment by colin-freemarketfx** [comment]
Nice one, thanks @skoruba
