### ISSUE TITLE
Docker Hub - Architecture not amd64

### ISSUE THREAD

**Issue by marcantoinecouture** [skoruba/Duende.IdentityServer.Admin#194]
### Describe the bug
Previous arch version of images were "linux/amd64". Since 2.0.0, arch is "linux/arm64".

Can you push a "amd64" version of the images?

### To Reproduce
See OS/ARCH of last tags.

### Relevant parts of the log file
N/A

Thank you

**Comment by skoruba** [comment]
Hi @marcantoinecouture  - thanks for letting me know. I built images from my MacBook now. Let me check it.

**Comment by markogl** [comment]
Any updates about this?

**Comment by skoruba** [comment]
@markogl - Sorry Marko for delay, I will push it next week, currently I am busy. 👍

**Comment by skoruba** [comment]
I published new docker images to amd architecture now. please check it, it is new release/2.1.0.

thank you!

**Comment by marcantoinecouture** [comment]
@skoruba I'll test the images soon. Will you publish arm64 images too?

**Comment by skoruba** [comment]
No, only amd64, do you need also arm64?

**Comment by skoruba** [comment]
Hi @marcantoinecouture - I am testing it on my linux server and I am getting this error:

> standard_init_linux.go:228: exec user process caused: exec format error

I tried use linux/amd64 as platfrom:

> docker buildx build --platform linux/amd64 

Any idea how to fix it? Maybe I missed something in DockerFile?

thanks

**Comment by marcantoinecouture** [comment]
Hi @skoruba 

I tested on my MacBook Pro (with amd64 images) and I got errors. I compiled the project locally and it works well. Probably emulation errors.

I tested on a Windows 11 VM (WSL2, server on amd64 architecture) with amd64 images from Docker Hub and it works fine.

> No, only amd64, do you need also arm64?

I think it's a good idea to push both on Docker Hub. There will be fewer errors with no emulation or need to local compile.

> Hi @marcantoinecouture - I am testing it on my linux server and I am getting this error:
> 
> > standard_init_linux.go:228: exec user process caused: exec format error
> 
> I tried use linux/amd64 as platfrom:
> 
> > docker buildx build --platform linux/amd64
> 
> Any idea how to fix it? Maybe I missed something in DockerFile?
> 
> thanks

Is your Linux server on a ARM? I think I got this error 2 years ago on my MacBook Pro M1 when I launched the project with amd64 images (with no emulation). I don't have a Linux server dev environment (such as Ubuntu Server) to test but I could build one to test.
I already compiled the 2.0.0 version of the project using the `--platform="linux/amd64"` and it works fine on Linux amd64 VM.

**Comment by skoruba** [comment]
Hi @marcantoinecouture - can you please help me with this? I struggle with it. :)

**Comment by marcantoinecouture** [comment]
Hi @skoruba,

Yes, I can help you with this. What is your Linux Server's environment?

**Comment by marcantoinecouture** [comment]
Good, and if you `docker image inspect IMAGE_NAME`, do you get `"Architecture": "amd64"` in the JSON file?

**Comment by skoruba** [comment]
I try this: `docker image inspect skoruba/duende-identityserver-admin:2.1.0` and get `"Architecture": "amd64", "Os": "linux"`. 
Any ideas?

**Comment by marcantoinecouture** [comment]
That's strange... Which Linux OS you use? I'll build a new dev environment.

**Comment by skoruba** [comment]
Finally I fixed it. It was incorrectly setup dockerfile unfortunately. I will push new version soon, but in docker hub are images taged as 2.1.0-amd64 👍

**Comment by marcantoinecouture** [comment]
Hi @skoruba - There's no arm64 version in docker hub. Can you push both under the same `2.1.0` tag?

**Comment by skoruba** [comment]
Hi @marcantoinecouture - sure, I can do it. so is it possible to generate tag 2.1.0 for both platform?

**Comment by skoruba** [comment]
It is done - please test version 2.2.2.

Thanks!

**Comment by marcantoinecouture** [comment]
It works, thank you!
