### ISSUE TITLE
I have a PR in the wings to allow the AdminIdentityDbContext TableNames to be defined in the appsettings

### ISSUE THREAD

**Issue by bclementfidx** [skoruba/Duende.IdentityServer.Admin#195]
I have a PR ready to go but I dont have permission to push.
My organization is looking to use your admin solutions over AdminUI but a big pain point for us is that we leverage the AspNet* table names and ideally we'd like to be able to use your solution without having to maintain any ongoing code changes (i.e. TableConsts.cs)

I have a PR where It will read the table names for AdminIdentityDbContext from the appsettings instead.

Would you be willing to take a look? We really like your product and it's just as good (if not better) than AdminUI and we'd forever use it and help out with issues/features along the way...

**Comment by skoruba** [comment]
Sure, I would like to see what you prepared.
Thanks!
