### ISSUE TITLE
Where can I learn about the new identity providers menu?

### ISSUE THREAD

**Issue by yunlang** [skoruba/Duende.IdentityServer.Admin#209]
### Question
I want to know about the new Identity Providers.
I'd like to see related documentation or feature descriptions.
What is it used for?

![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/1518611/52a6bea9-44f5-4ac4-ac96-a9193c8659ff)

![image](https://github.com/skoruba/Duende.IdentityServer.Admin/assets/1518611/619bbde6-3dca-4037-b948-c0e039d48547)

**Comment by skoruba** [comment]
Please, check these properties for OIDC middleware:

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions?view=aspnetcore-8.0

Thanks
