### ISSUE TITLE
Migrate from Microsoft.Azure.KeyVault to the new Azure Key Vault API

### ISSUE THREAD

**Issue by marisks** [skoruba/Duende.IdentityServer.Admin#224]
The old API has some issues:
https://stackoverflow.com/questions/63608985/azure-app-service-with-user-assigned-managed-identity-crashes-application

It also might not be supported in the future.

The documentation for the new API: 
https://learn.microsoft.com/en-us/azure/key-vault/general/

**Comment by skoruba** [comment]
Released in 2.4.0. 
Thanks!
