### ISSUE TITLE
Sessions appear to be shared.

### ISSUE THREAD

**Issue by heesung-ich** [skoruba/Duende.IdentityServer.Admin#225]
### Question

 - When a user logged into ``ciba`` with identity ``connect/userinfo`` requests user information, it is returning the information of someone else who logged in earlier, even though I send the normal access_token information 
 - It's as if the session is being shared, and I need help with what settings I should be looking at.

**Comment by skoruba** [comment]
Hi @heesung-ich - sorry for delay answer, did you find solution for your scenario?
