### ISSUE TITLE
Can't update client because "Client Id _clientId_ already exists"

### ISSUE THREAD

**Issue by pavvlik777** [skoruba/Duende.IdentityServer.Admin#227]
### Describe the bug
When clicking 'Save Client' button client is not updated and 'Client Id _clientId_ already exists' error received

### To Reproduce
1. Click 'Edit' any existing client
2. Click 'Save Client'
#### Result
Error received
![image](https://github.com/user-attachments/assets/683c8c8f-7e02-4f45-b49b-81ea400c9cf5)
#### Expected result
Client is successfully updated

### Notes
It appears that issue is caused by missing ```<input type="hidden" asp-for="Id" />``` tag on client configuration page. Because of that model.Id is 0 on POST request and backend trying to create client rather than update existing. Issue wasn't happening on 1.1.0 version, because there was tag on basics tab.

**Comment by skoruba** [comment]
Hi @pavvlik777 - thanks for reporting your issue, I will check it!

**Comment by skoruba** [comment]
I have checked it and it works for me correctly. Id is not stored in hidden field but it is correctly populated from URL.
Are you sure that you do not have some client twice?
Thanks.

**Comment by pavvlik777** [comment]
Hi, thanks for response.

I double-checked client id and didn't find any duplicates in db.
![image](https://github.com/user-attachments/assets/9a0dda80-3e29-4076-af29-d40c99ce3e68)
I was able to reproduce same issue by creating new client and clicking 'save client' immediately after that. I was redirected to creation page and id disappeared from URL.
![image](https://github.com/user-attachments/assets/4eedb5a7-c6b4-4493-a9c5-8a35b494247f)

Also I noticed that adding clientId manually to form URL like this 
![image](https://github.com/user-attachments/assets/c4b496e9-c21b-4eb7-bf7f-a0c5423ed3b9)
fixes issue.

**Comment by pavvlik777** [comment]
2.3.0

**Comment by skoruba** [comment]
Let me check it again.

Adding of `<input type="hidden" asp-for="Id" />` resolved this issue?

**Comment by pavvlik777** [comment]
Yes

**Comment by skoruba** [comment]
OK, I will merge your PR and release it in release 2.4.0.
Thank you.

**Comment by skoruba** [comment]
Can you also check console in your browser in case that you have some JS errors?

**Comment by skoruba** [comment]
Why do you have `?area=AdminUI` in your links?

**Comment by pavvlik777** [comment]
Looks like it's added automatically on all links, but there were no specific adjustments to achieve this from my side.
![image](https://github.com/user-attachments/assets/f4048b33-7a29-4a60-a0e5-dccafe180db6)

**Comment by skoruba** [comment]
Ok, interesting, I have never seen it before. 😁

**Comment by skoruba** [comment]
Released in 2.4.0. 
Thanks!
