### ISSUE TITLE
Skoruba.Duende.IdentityServer.Shared.Configuration - replace deprecated Microsoft.Extensions.Configuration.AzureKeyVault package with Azure.Extensions.AspNetCore.Configuration.Secrets

### ISSUE THREAD

**Issue by omon77** [skoruba/Duende.IdentityServer.Admin#234]
### Issue
Skoruba.Duende.IdentityServer.Shared.Configuration project references Microsoft.Extensions.Configuration.AzureKeyVault package, which has been deprecated, and is using Microsoft.Rest.ClientRuntime v2.3.8 which has also been deprecated and has security vulnerability.

The drop-in replacement for Microsoft.Extensions.Configuration.AzureKeyVault is Azure.Extensions.AspNetCore.Configuration.Secrets (currently v1.3.2).

**Comment by skoruba** [comment]
I will update whole solution with the latest version of packages, thanks!

**Comment by skoruba** [comment]
Released in 2.4.0. 
Thanks!
