### ISSUE TITLE
MySQL migration issue

### ISSUE THREAD

**Issue by skoruba** [skoruba/Duende.IdentityServer.Admin#25]
This issue related to this issue: https://github.com/skoruba/IdentityServer4.Admin/issues/847

**Comment by bitai-cs** [comment]
The problem is caused by the following line in the migration scripts: "longtext CHARACTER SET utf8mb4(4000)"
The data type 'longtext' should not be assigned a specific length.

I overcame the problem by removing the HasMaxLength (4000) from the migration scripts.

**Comment by skoruba** [comment]
@bitai-cs - thanks - I will update the package and fix the db migration script for mysql.

**Comment by skoruba** [comment]
Fixed in 1.0.0
