### ISSUE TITLE
Supporting next version of Identity Server

### ISSUE THREAD

**Issue by meysamhadeli** [skoruba/Duende.IdentityServer.Admin#32]
Hi.
what is your plan for upgrading to next version of identity server and its licence?

- [ASP.NET Core 6 and authentication servers: the real bait and switch is not the one you think](https://kevinchalet.com/2021/05/24/asp-net-core-6-and-authentication-servers-the-real-bait-and-switch-is-not-the-one-you-think/)
- [ASP.NET Core 6 and Authentication Servers](https://devblogs.microsoft.com/aspnet/asp-net-core-6-and-authentication-servers/)

**Comment by skoruba** [comment]
Hello @meysamhadeli 

I continue on this project, I will definitely provide the Admin UI for Duende IdentityServer. 😊

Thanks!
