### ISSUE TITLE
Should the docker-compose.vs.*.yml reference .NET 6?

### ISSUE THREAD

**Issue by VictorioBerra** [skoruba/Duende.IdentityServer.Admin#54]
### Describe the bug
I am struggling to get Docker to work. 

- Windows 10
- Docker
- WSL2
- Ubuntu
- Visual Studio 2022
- .NET 6
- Skoruba.Duende.IdentityServer.Admin.Templates::1.1.0

https://github.com/skoruba/Duende.IdentityServer.Admin/blob/63a89aaae7e4e22731305756825eff3ec184ad07/templates/template-publish/content/docker-compose.vs.debug.yml#L8

### To Reproduce

- `dotnet new skoruba.duende.isadmin --name MySkApp --title "MySkApp" --adminemail "MySkApp@MySkApp.com" --adminpassword "Pa$$word123" --adminrole Admin --adminclientid SkorubaAdminClient --adminclientsecret SkorubaAdminClientSecret --dockersupport true`
- Edit hosts file on windows, add `127.0.0.1 skoruba.local sts.skoruba.local admin.skoruba.local admin-api.skoruba.local`
- Open powershell:
    - `cd shared/nginx/certs; mkcert --install; copy $env:LOCALAPPDATA\mkcert\rootCA.pem ./cacerts.pem; copy $env:LOCALAPPDATA\mkcert\rootCA.pem ./cacerts.crt`;
- Open solution in VS 2022, click the play button, it should say "Docker Compose"

### Relevant parts of the log file
![image](https://user-images.githubusercontent.com/2934507/154999483-ff546bba-d22f-48ad-83b7-fac0e15cef69.png)

![image](https://user-images.githubusercontent.com/2934507/154999640-c747c55b-e8e0-47fe-9184-3a591260854b.png)

![image](https://user-images.githubusercontent.com/2934507/154999967-256662b0-6e89-4792-acd0-6b505094b669.png)

![image](https://user-images.githubusercontent.com/2934507/154999790-50a34a7b-d5de-4c98-becc-75440b8b4e59.png)

```
<log goes here>
```

**Comment by skoruba** [comment]
Hello @VictorioBerra - thank you, I will fix it. 👍

**Comment by swmolen** [comment]
I found this too. you can go ahead and close my issue, this one is much better documented.
