### ISSUE TITLE
Authorization error in API

### ISSUE THREAD

**Issue by coumarc9** [skoruba/Duende.IdentityServer.Admin#6]
### Describe the bug
*I'm using Docker on Linux*
I try to use Swagger to call the endpoints of the API, but I always get this error:
```
[INFO][13][Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed. "These requirements were not met:\nHandler assertion should evaluate to true."
[INFO][13][Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler] AuthenticationScheme: "Identity.Application" was challenged.
```
I also get the same error using the images from Docker Hub (tag: preview3)
I tried to change the authorization policy (debugging), it seems that the authenticated user doesn't have claims:
https://github.com/skoruba/Duende.IdentityServer.Admin/blob/a07a55f2bf12f53e385eff861328637d90a7d1f6/src/Skoruba.Duende.IdentityServer.Admin.Api/Helpers/StartupHelpers.cs#L249-L263

### To Reproduce
1. `git clone`
2. Delete the volumes in `docker-compose.override.yml`
3. `docker-compose build`, `docker-compose up`
4. Go to Swagger, login and 

I also made some changes in URLs (use xip.io instead of skoruba.local, HTTP instead of HTTPS, no certificates), but the same changes work in "IdentityServer4.Admin" project. I don't think these changes are problems.

**Comment by skoruba** [comment]
Hello @coumarc9 - I will check it, thanks!

**Comment by skoruba** [comment]
I fixed this issue in the release `1.0.0-preview5`, which is available in the master branch now.

Could you please test it? 😊

Thanks

**Comment by coumarc9** [comment]
Hello,

I tested and it's fixed now.

Thank you!

**Comment by skoruba** [comment]
Thank you for your feedback 👍
