### ISSUE TITLE
How to add profile service correctly (.AddIdentityServer(...).AddProfileService(...)) ?

### ISSUE THREAD

**Issue by itoop2019** [skoruba/Duende.IdentityServer.Admin#7]
**If I add a service profile, then there is no access to IdentityServer.Admin.**

![image](https://user-images.githubusercontent.com/47772383/115961808-b76f6700-a520-11eb-93d0-65a8774fdda8.png)

**It doesn't matter what the class does, the very fact of adding this class breaks something.**

```
public class ProfileService<TUser> : IProfileService
        where TUser : UserIdentity
   {
      private readonly UserManager<TUser> _userManager;

      public ProfileService(UserManager<TUser> userManager)
      {
          _userManager = userManager;
      }

      public async Task GetProfileDataAsync(ProfileDataRequestContext context)
      {
         //var user = await _userManager.GetUserAsync(context.Subject);
         //if (user is null)
         //   return;

         //var rolesUser = await _userManager.GetRolesAsync(user).ConfigureAwait(false);
         //string roles = String.Join(",", rolesUser);
        
         //var claims = new List<Claim>();
         //claims.Add(new Claim("custRoles", roles));

         //context.IssuedClaims.AddRange(claims);
      }

      public async Task IsActiveAsync(IsActiveContext context)
      {
        var user = await _userManager.GetUserAsync(context.Subject);
        context.IsActive = user != null;
      }
   }

```

**And when I try to login, I get:**
![image](https://user-images.githubusercontent.com/47772383/115962095-5d6fa100-a522-11eb-8bef-4ba14190cfde.png)

**Comment by skoruba** [comment]
It looks like that you do not have correct role claim for sign in into IS4 Admin. 
I think that you added the `ProfileService` correctly there.
Can you check that you have correct claims?
Thanks!

**Comment by itoop2019** [comment]
Thank you for the answer, I realized that the credits are lost, but it's strange that when this class is added. If the class is not added, then the admin works correctly

**Comment by skoruba** [comment]
You can check the default ProfileService: https://github.com/DuendeSoftware/IdentityServer/blob/main/src/AspNetIdentity/ProfileService.cs - you can compare your code.
Thanks

**Comment by itoop2019** [comment]
I figured it out, not yet completely, but it already worked. It turns out that if you use ProfileService, then the Clams will be removed and you need to add the ones you need yourself. And I thought that the existing Clams are not deleted and my new ones will reach them.

Thank you!

**Comment by itoop2019** [comment]
Thanks

**Comment by zarinbal** [comment]
I had the same issue.  I had two problems:

1. IsUserActiveAsync was returning false for admin user
2. Claims were lost.

According to https://github.com/DuendeSoftware/IdentityServer/blob/main/src/AspNetIdentity/ProfileService.cs, I implemented the  `GetUserClaimsAsync(TUser user)` like this

`      protected virtual async Task<ClaimsPrincipal> GetUserClaimsAsync(TUser user)
        {
            var principal = await ClaimsFactory.CreateAsync(user);
            if (principal == null) throw new Exception("ClaimsFactory failed to create a principal");

            return principal;
        }
`

Then in the `GetProfileDataAsync` function, I add the Claims

```
protected virtual async Task GetProfileDataAsync(ProfileDataRequestContext context, TUser user)
        {
            var principal = await GetUserClaimsAsync(user);
            context.AddRequestedClaims(principal.Claims);
// Here you can add the rest of the claims you need

}
```
