### ISSUE TITLE
Upgrade to Duende.IdentityServer.* version 6.1.0

### ISSUE THREAD

**Issue by senzacionale** [skoruba/Duende.IdentityServer.Admin#79]
Hello,

Do you plan to make an upgrade to Duende.IdentityServer.* to version 6.1?

```
<PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="6.1.0" />
 <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="6.1.0" />
```

**Comment by senzacionale** [comment]
@skoruba any plans about that?

**Comment by skoruba** [comment]
Hello, I will do it. Thanks!

**Comment by senzacionale** [comment]
Hello. Great to hear that. Thanks!

**Comment by skoruba** [comment]
I will do it in the next version 1.2.0 - #56

**Comment by senzacionale** [comment]
Great to hear. Thank you

**Comment by senzacionale** [comment]
Hi. Any plans about the upgrade?

**Comment by skoruba** [comment]
Hi @senzacionale - sorry for the delay - I will do it, but I do not know when. :) I will send update.

Thanks!

**Comment by michaelmarcuccio** [comment]
even better, update to Duende.IdentityServer.* version 6.2.0 now that it has released.

**Comment by skoruba** [comment]
I am sorry for the delay, it is work in progress I will publish it with the latest version of Duende IS.
