### ISSUE TITLE
Why automatic key management is disabled?

### ISSUE THREAD

**Issue by FabienDehopre** [skoruba/Duende.IdentityServer.Admin#9]
### Question
Is there any reason why you disabled the automatic key management in StartupHelper class in STS project?
Here is the line: https://github.com/skoruba/Duende.IdentityServer.Admin/blob/a07a55f2bf12f53e385eff861328637d90a7d1f6/src/Skoruba.Duende.IdentityServer.STS.Identity/Helpers/StartupHelpers.cs#L351

I'm asking because I've just read an article on the blog of Duende Software about automatic key management feature they've added. https://blog.duendesoftware.com/posts/20201028_key_management/

**Comment by skoruba** [comment]
Hello @FabienDehopre - good question, I disabled this feature for my first preview version, I wanted keep migration easier from IS4 Admin. I will enable this feature for next preview version, that is great feature for sure. 😊 You can enable automatic key management by your own, but I will do it as well.
Thanks!

**Comment by FabienDehopre** [comment]
Thanks @skoruba. 
Indeed, I was planning to enable it in my fork.

**Comment by FabienDehopre** [comment]
FYI: the automatic key management feature is a licensed feature and cannot be activated in community edition apparently.

**Comment by skoruba** [comment]
@FabienDehopre - Yes, it is - I will generate EF migrations for easier configuration. 😊
