### ISSUE TITLE
Why is identity server issuer localhost?

### ISSUE THREAD

**Issue by Removable** [skoruba/Duende.IdentityServer.Admin#99]
I created my project using `Skoruba.Duende.IdentityServer.Admin.Templates` and deployed the solution on my server via docker-compose.

But all the addresses in `openid-configuration` are localhost (I had already set `IssuerUri` in the environment with docker-compose.yml):

```
{"issuer":"http://localhost","jwks_uri":"http://localhost/.well-known/openid-configuration/jwks","authorization_endpoint":"http://localhost/connect/authorize","token_endpoint":"http://localhost/connect/token","userinfo_endpoint":"http://localhost/connect/userinfo","end_session_endpoint":"http://localhost/connect/endsession",...}
```

So I want to know if there are any configurations I missed, please help me! Thanks in advance!

**Comment by Removable** [comment]
fixed

**Comment by Myrdrahl** [comment]
How was this fixed, as we seem to be experiencing the same issue.
